### ISSUE TITLE
gulp failed

### ISSUE THREAD

**Issue by stereodenis** [alexfedoseev/isomorphic-comments-app#3]
```
gulp start:dev
[23:52:16] Requiring external module babel-core/register
[23:52:17] Using gulpfile ~/work/test/isomorphic-comments-app/gulpfile.babel.js
[23:52:18] Starting 'start:dev'...
[23:52:18] Starting 'clean'...
[23:52:18] Starting 'lint'...
[23:52:18] 'lint' errored after 738 ms
[23:52:18] TypeError: Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function
    at Function.componentRule (/Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint-plugin-react/lib/util/Components.js:107:28)
    at /Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/eslint.js:628:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/eslint.js:619:16)
    at processText (/Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/cli-engine.js:322:26
    at /Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/stereodenis/work/test/isomorphic-comments-app/node_modules/eslint/lib/util/traverse.js:41:54)
[23:52:18] 'start:dev' errored after 749 ms
[23:52:18] Error in plugin 'run-sequence'
```

**Comment by alexfedoseev** [comment]
@stereodenis This is very old setup, a lot of deps were updated. Currently I'm rewriting this stack, gulp is out, bunch of things were added (CSS Modules, Immutable.js etc) and the whole flow was changed. I'll publish new version of it hopefully till the end of the year. Here is the source repo: https://github.com/alexfedoseev/generator-flux-on-rails

**Comment by stereodenis** [comment]
@alexfedoseev thanks! I'm trying it now
