### ISSUE TITLE
WARN deprecated and error when try this app

### ISSUE THREAD

**Issue by im-kulikov** [alexfedoseev/isomorphic-comments-app#4]
When `npm install`

```
npm WARN deprecated css-list@0.1.3: Deprecated.

npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

npm WARN prefer global marked@0.3.5 should be installed with -g
```

**Comment by im-kulikov** [comment]
```
↪ npm start                                                                                                                                                               19:16:30

> isomorphic-comments-app@0.0.1 start /Users/kulikov-im/Downloads/isomorphic-comments-app-master
> gulp start:dev

[19:16:57] Failed to load external module babel-register
[19:16:57] Requiring external module babel-core/register
[19:16:58] Using gulpfile ~/Downloads/isomorphic-comments-app-master/gulpfile.babel.js
[19:16:58] Starting 'start:dev'...
[19:16:58] Starting 'clean'...
[19:16:58] Starting 'lint'...
[19:16:59] 'lint' errored after 788 ms
[19:16:59] TypeError: Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function
    at Function.componentRule (/Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint-plugin-react/lib/util/Components.js:109:28)
    at /Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/eslint.js:628:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/eslint.js:619:16)
    at processText (/Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/cli-engine.js:322:26
    at /Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/kulikov-im/Downloads/isomorphic-comments-app-master/node_modules/eslint/lib/util/traverse.js:41:54)
[19:16:59] 'start:dev' errored after 799 ms
[19:16:59] Error in plugin 'run-sequence'
Message:
    An error occured in task 'lint'.
[19:16:59] Finished 'clean' after 815 ms

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! isomorphic-comments-app@0.0.1 start: `gulp start:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic-comments-app@0.0.1 start script 'gulp start:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the isomorphic-comments-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs isomorphic-comments-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls isomorphic-comments-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kulikov-im/Downloads/isomorphic-comments-app-master/npm-debug.log
```
